# Generated by Django 2.0.3 on 2020-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200715_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='upload/21.jpg', upload_to='upload', verbose_name='图片'),
        ),
    ]
